### ISSUE TITLE
How to contribute to  Bannedapps.uk ?

### ISSUE THREAD

**Issue by zainulhasan** [NIWebDesigns/Bannedapps.uk#4]
Hello There,

I want to contribute to Bannedapps. Please guide me on how can I be helpful.

Thanks,
Zain

**Comment by itsmat32143** [comment]
Thanks alot mate that means alot to me 😋 um things you could do to help

Donate to help with domain costs
Help with design and building giving ideas

**Comment by zainulhasan** [comment]
> Thanks alot mate that means alot to me 😋 um things you could do to help
> 
> 1. Donate to help with domain costs
> 2. Help with design and building giving ideas or submitting code
> 3. Checking Links
> 4. Spread the word get more people using the app
> 
> Sorry about closing this hit it by mistake i will add to the repository later

I can help you build new apps. Let's build something to gather.

Thanks,

**Comment by itsmat32143** [comment]
What do you have in mind?
